sdk:
  api:
    #    url: ssl://183.230.102.116:8883  加密连接
    url: tcp://mqtts.heclouds.com:1883
#    # 产品ID
#    product-id: vOCKMQW4sv
#    # 产品key
#    access-key: X2cTAfsZ33XdP9URsfuLtQO3Z88TgUWZiY0Jg23nf5s=

    # 产品ID
    product-id: ku6G2Oeaj5
    # 产品key
    access-key: q/HdO+97w09fHdu/XVMxx70lS32/5yEno7GFP115/80=
